apiVersion: v1
kind: Service
metadata:
    name: redirectionio-proxy
    labels:
        app: demo
spec:
    ports:
        - port: 80
    selector:
        app: demo
        tier: proxy
    type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: redirectionio-proxy
    labels:
        app: demo
spec:
    selector:
        matchLabels:
            app: demo
            tier: proxy
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: demo
                tier: proxy
        spec:
            containers:
                - image: gcr.io/redirection-io-test/nginx-proxy:v1
                  name: redirectionio-proxy
                  ports:
                      - containerPort: 80
                        name: proxy
